# Generated by Django 5.1.2 on 2024-11-04 00:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('user_name', models.CharField(max_length=50, unique=True)),
                ('user_password', models.CharField(max_length=128)),
                ('user_profile', models.ImageField(blank=True, null=True, upload_to='profiles/')),
                ('user_email', models.EmailField(max_length=254, unique=True)),
                ('user_birth', models.DateField(blank=True, null=True)),
                ('admin', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
