# Generated by Django 5.1.2 on 2024-11-08 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_diary'),
    ]

    operations = [
        migrations.AddField(
            model_name='diary',
            name='emotion',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
