# Generated by Django 5.1.2 on 2024-11-08 08:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_diary_emotion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='diary',
            name='emotion',
        ),
    ]
