# Generated by Django 5.1.2 on 2024-11-08 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_diary_emotion_alter_diary_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diary',
            name='created_at',
            field=models.DateField(),
        ),
    ]
