# Generated by Django 5.1.2 on 2024-11-12 00:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_alter_diary_created_at'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Diary',
        ),
    ]
