# Generated by Django 5.1.2 on 2024-12-02 02:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0003_hashtag_post_hashtags'),
        ('movies', '0005_movies_poster_path_movies_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hashtag',
            name='movie',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='hashtags', to='movies.movies'),
        ),
    ]
