# Generated by Django 5.1.2 on 2024-12-02 05:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0004_alter_hashtag_movie'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hashtag',
            old_name='movie',
            new_name='movies',
        ),
    ]
