# Generated by Django 5.1.2 on 2024-12-02 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0005_rename_movie_hashtag_movies'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hashtag',
            name='movies',
        ),
        migrations.AlterField(
            model_name='hashtag',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
