# Generated by Django 5.1.2 on 2024-11-11 06:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0003_review_dislikes_review_likes_review_updated_at_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='dislikes',
            new_name='dislike_count',
        ),
        migrations.RenameField(
            model_name='review',
            old_name='likes',
            new_name='like_count',
        ),
    ]
