# Generated by Django 5.1.2 on 2024-11-15 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0008_reviewreport'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reviewreport',
            name='block_user',
        ),
        migrations.RemoveField(
            model_name='reviewreport',
            name='other_reason',
        ),
        migrations.RemoveField(
            model_name='reviewreport',
            name='processed',
        ),
        migrations.AlterField(
            model_name='reviewreport',
            name='reason',
            field=models.CharField(choices=[('spam', '도배성 게시물'), ('inappropriate', '부적절한 내용'), ('false_info', '거짓 정보')], max_length=50),
        ),
    ]
