# Generated by Django 5.1.2 on 2024-11-18 01:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0009_remove_reviewreport_block_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='reviewreport',
            name='processed',
            field=models.BooleanField(default=False),
        ),
    ]
