# Generated by Django 5.1.2 on 2024-11-18 02:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0011_reviewreport_is_active'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reviewreport',
            name='is_active',
        ),
        migrations.AddField(
            model_name='review',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
