# Generated by Django 5.1.2 on 2024-11-18 02:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0012_remove_reviewreport_is_active_review_is_active'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='is_active',
        ),
    ]
