# Generated by Django 5.1.2 on 2024-11-08 00:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='movies',
            name='poster_path',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
