# Generated by Django 5.1.2 on 2024-11-08 00:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0002_movies_poster_path'),
    ]

    operations = [
        migrations.AddField(
            model_name='movies',
            name='title',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
