# Generated by Django 5.1.2 on 2024-12-02 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0006_remove_hashtag_movies_alter_hashtag_name'),
        ('movies', '0005_movies_poster_path_movies_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='movies',
            name='hashtags',
            field=models.ManyToManyField(related_name='movies', to='community.hashtag'),
        ),
    ]
